#
# Copyright 2021 William Swartzendruber
#
# Any copyright is dedicated to the Public Domain.
#
# SPDX-License-Identifier: CC0-1.0
#

accepted = [
    "MPL-2.0",
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
]
